import $plugin.$ivy.`org.scalamacros:::paradise:2.1.1`
import $ivy.`com.lihaoyi::ammonite-ops:1.2.1`
import $ivy.`com.github.pathikrit::better-files:3.6.0`
import $ivy.`com.nrinaudo::kantan.csv:0.4.0`
import $ivy.`com.nrinaudo::kantan.csv-generic:0.4.0`
import $ivy.`org.typelevel::cats-effect:0.10`
import $ivy.`io.circe::circe-core:0.9.3`
import $ivy.`io.circe::circe-generic:0.9.3`
import $ivy.`io.circe::circe-jackson29:0.9.0`
import $ivy.`com.storm-enroute::scalameter:0.10.1`
import $ivy.`com.pepegar::hammock-core:0.8.6`
import $ivy.`com.pepegar::hammock-circe:0.8.6`
