#!/bin/bash
tmpDir=$(mktemp -d /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution/tmp.XXXXXX)
chmod 777 $tmpDir
export _JAVA_OPTIONS=-Djava.io.tmpdir=$tmpDir
export TMPDIR=$tmpDir

(
cd /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution
echo condition=Day13_A experiment=GSM1696300
)
echo $? > /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution/rc.tmp
(
cd /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution

)
sync
mv /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution/rc.tmp /home/antonkulaga/rna-seq/workflows/test/cromwell-executions/test/ea3cf15f-c8a9-4d68-8bcd-5871effc42ef/call-tracer/shard-3/tracer/8f7553a3-6881-4edb-85c4-15f192ea8306/call-trace/shard-3/execution/rc
